import type { Metadata } from "next";
import { spaceGrotesk, inter, ebGaramond } from '@/app/ui/fonts';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className={`${spaceGrotesk.variable} ${inter.variable} ${ebGaramond.className} min-h-full flex flex-col antialiased`}>
        {children}
      </body>
    </html>
  );
}